

export const users=[
  {
    "firstname": "Kasandra",
    "lastname": "Schulist",
    "avatar": "https://avatars.githubusercontent.com/u/20927864",
    "email": "Kiley_King@gmail.com",
    "number": "1-266-206-0173 x59590",
    "city": "Chelseaborough",
    "adres": "Phoenix",
    "job": "Orchestrator",
    "id": "1",
    "uroven":"junior",
    "tip":"backend",
  },
  {
    "firstname": "Jordy",
    "lastname": "Krajcik",
    "avatar": "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/6.jpg",
    "email": "Maxine.Lowe@yahoo.com",
    "number": "1-906-311-7765 x179",
    "city": "New Kyleestead",
    "adres": "Redlands",
    "job": "Agent",
    "id": "2",
    "uroven":"middle",
    "tip":"frontend",
  },
  {
    "firstname": "Heather",
    "lastname": "Walter",
    "avatar": "https://avatars.githubusercontent.com/u/65300530",
    "email": "Elody.Brekke91@gmail.com",
    "number": "(398) 258-6711 x95342",
    "city": "Maeganville",
    "adres": "Wichita",
    "job": "Agent",
    "id": "3",
    "uroven":"middle",
    "tip":"frontend",
  },
  {
    "firstname": "Lexi",
    "lastname": "O'Hara-Crona",
    "avatar": "https://avatars.githubusercontent.com/u/77511755",
    "email": "Sedrick_Bartell-Mayert@gmail.com",
    "number": "302-704-1768",
    "city": "Kennithbury",
    "adres": "Fort Mozellefield",
    "job": "Officer",
    "id": "4",
    "uroven":"middle",
    "tip":"backend",
  },
  {
    "firstname": "Dusty",
    "lastname": "Littel",
    "avatar": "https://avatars.githubusercontent.com/u/13853031",
    "email": "Angie.Gibson@hotmail.com",
    "number": "396.823.5616 x605",
    "city": "Raynorshire",
    "adres": "Utica",
    "job": "Liaison",
    "id": "5",
    "uroven":"senior",
    "tip":"frontend",
  },
  {
    "firstname": "Kariane",
    "lastname": "Hamill",
    "avatar": "https://avatars.githubusercontent.com/u/87776165",
    "email": "Jazmyn.Funk@hotmail.com",
    "number": "(242) 593-3817",
    "city": "Pflugerville",
    "adres": "Julianneside",
    "job": "Agent",
    "id": "6",
    "uroven":"junior",
    "tip":"backend",
  },
  {
    "firstname": "Judah",
    "lastname": "Thiel",
    "avatar": "https://avatars.githubusercontent.com/u/55888764",
    "email": "Trever.Weissnat-Macejkovic22@hotmail.com",
    "number": "285.845.2505",
    "city": "East Bessie",
    "adres": "Runtecester",
    "job": "Orchestrator",
    "id": "7",
    "uroven":"senior",
    "tip":"backend",
  },
  {
    "firstname": "Theo",
    "lastname": "Breitenberg-Leffler",
    "avatar": "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/67.jpg",
    "email": "Lula45@yahoo.com",
    "number": "781.792.6204",
    "city": "Lake Uriahmouth",
    "adres": "Hanefurt",
    "job": "Analyst",
    "id": "8",
    "uroven":"junior",
    "tip":"backend",
  },
  {
    "firstname": "Jessica",
    "lastname": "McKenzie",
    "avatar": "https://avatars.githubusercontent.com/u/42308028",
    "email": "Esteban25@gmail.com",
    "number": "456.301.7701 x80106",
    "city": "Tyler",
    "adres": "Norbertburgh",
    "job": "Associate",
    "id": "9",
    "uroven":"middle",
    "tip":"backend",
  },
  {
    "firstname": "Jedidiah",
    "lastname": "Purdy",
    "avatar": "https://avatars.githubusercontent.com/u/90917960",
    "email": "Jada.Lehner@yahoo.com",
    "number": "1-878-287-1201 x78796",
    "city": "Aishaton",
    "adres": "Thornton",
    "job": "Liaison",
    "id": "10",
    "uroven":"junior",
    "tip":"frontend",
  },
  {
    "firstname": "Abelardo",
    "lastname": "Price",
    "avatar": "https://avatars.githubusercontent.com/u/91196509",
    "email": "Mina.Torp29@yahoo.com",
    "number": "1-749-978-0940 x9379",
    "city": "Jonesboro",
    "adres": "Huntington Beach",
    "job": "Representative",
    "id": "11",
    "uroven":"junior",
    "tip":"backend",
  },
  {
    "firstname": "Joany",
    "lastname": "Koelpin-Senger",
    "avatar": "https://avatars.githubusercontent.com/u/14910096",
    "email": "Rebekah.Treutel27@yahoo.com",
    "number": "1-846-377-3247",
    "city": "Osinskitown",
    "adres": "Spokane",
    "job": "Producer",
    "id": "12",
    "uroven":"senior",
    "tip":"frontend",
  },
  {
    "firstname": "Pedro",
    "lastname": "Bins",
    "avatar": "https://avatars.githubusercontent.com/u/94000821",
    "email": "Amari.Hermiston69@yahoo.com",
    "number": "1-308-711-1575 x451",
    "city": "Schummhaven",
    "adres": "Amarillo",
    "job": "Technician",
    "id": "13",
    "uroven":"junior",
    "tip":"frontend",
  },
  {
    "firstname": "Juwan",
    "lastname": "Kub",
    "avatar": "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/6.jpg",
    "email": "Dario15@hotmail.com",
    "number": "(490) 458-1369 x088",
    "city": "East Malvinaside",
    "adres": "Everettefield",
    "job": "Associate",
    "id": "14",
    "uroven":"junior",
    "tip":"frontend",
  },
  {
    "firstname": "Garrett",
    "lastname": "Beer",
    "avatar": "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/7.jpg",
    "email": "Olaf59@hotmail.com",
    "number": "1-494-777-5293 x2289",
    "city": "Ceciliabury",
    "adres": "Shoreline",
    "job": "Supervisor",
    "id": "15",
    "uroven":"senior",
    "tip":"backend",
  },
  {
    "firstname": "Ned",
    "lastname": "Rowe",
    "avatar": "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/3.jpg",
    "email": "Lourdes_Ferry59@yahoo.com",
    "number": "1-391-209-1820 x35052",
    "city": "West Jordan",
    "adres": "West Raleigh",
    "job": "Manager",
    "id": "16",
    "uroven":"junior",
    "tip":"fullstack",
  }
  
]